app/views.py
import logging
import random
import json

from google.appengine.ext import db

from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for

from flask_login import login_required
from flask_login import current_user

from app.models import student
from app.models import user
from app.models import isu

blueprint = Blueprint('views', __name__)


@blueprint.route('/', methods=['GET'])
def home():
    return render_template('home.html')


@blueprint.route('/charts', methods=['GET', 'POST'])
def charts():

    if not current_user.is_authenticated():
        return redirect(url_for('views.home'), code=302)
    if request.method == 'POST':
        student_query = student.Student.all()
        students = student_query.fetch(limit=None)
        query_form = request.form
        college = query_form.get('college')
        major = query_form.get('major')
        student_type = query_form.get('student_type')
        year = query_form.get('year')
        course = query_form.get('course')

        try:
            year = int(year)
        except ValueError:
            pass


        students = []
        if course:
            student_query = student.Student.all().filter('course', course)
        elif major:
            student_query = student.Student.all().filter('major', major)
        elif college:
            student_query = student.Student.all().filter('college', college)
        else:
            student_query = student.Student.all()

        if year == 'all':
            students = student_query.fetch(limit=None)
        else:
            students = student_query.filter('year', year).fetch(limit=None)


        distribution = {}
        grades = ['A','A-','B+','B','B-','C+','C','C-','D+','D','D-','F']

        for s in students:
            key = getattr(s, student_type)

            if student_type == 'gpa':
                key = "%.1f" % (key,)
            elif student_type == 'gender':
                key = 'Male' if key else 'Female'
            elif student_type == 'oncampus':
                key = 'On Campus' if key else 'Off Campus'
            elif student_type == 'major':
                key = s.major
            elif student_type == 'grade':
                if s.grade is None:
                    s.grade = random.choice(['A','A-','B+','B','B-','C+','C','C-','D+','D','D-','F'])
                key = s.grade
                for g in grades:
                    distribution[s.year] = distribution.get(s.year, {})
                    distribution[s.year][g] = distribution[s.year].get(g, 0)


            distribution[s.year] = distribution.get(s.year, {})
            distribution[s.year][key] = distribution[s.year].get(key, 0) + 1
            logging.info("value of distribution at s.year = %s and key = %s is %s", s.year, key, distribution[s.year].get(key, 0))
        return json.dumps({
            'distribution': distribution
        })


    return render_template('chart.html', colleges=isu.colleges.keys())


@blueprint.route('/isu/<college>/', methods=['GET'])
def iowa_state(college):
    return json.dumps(isu.colleges.get(college, []))


@blueprint.route('/auth/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('views.home'), code=302)

    if request.method == 'POST':
        login_form = request.form

        user.login(login_form.get('email'), login_form.get('password'))

        if current_user.is_authenticated():
            next_url = request.args.get('next',url_for('views.home'))
            return redirect(next_url, code=302)
        else:
            return render_template('login.html', failure=True, email=login_form.get('email'))

    return render_template('login.html', failure=False, email='')


@blueprint.route('/auth/logout', methods=['GET'])
def logout():
    user.logout()
    return redirect(url_for('views.home'), code=302)


@blueprint.route('/auth/register/<registration_id>', methods=['GET', 'POST'])
def register(registration_id):
    new_user = user.get_by_registration_id(registration_id)
    if not new_user or new_user.is_registered:
        return redirect(url_for('views.home'), code=302)

    if request.method == 'POST':
        registration_form = request.form
        new_password = registration_form.get('password', '')
        if len(new_password) < 6:
            return render_template('register.html', attempt={'failure':True}, user=new_user)

        user.register(registration_id, new_password)
        return redirect(url_for('views.home'), code=302)

    return render_template('register.html', attempt={}, user=new_user)


@blueprint.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    if not current_user.is_admin():
        return redirect(url_for('views.home'), code=302)

    if request.method == 'POST':
        admin_form = request.form
        user_role = admin_form.get('role', user.BASE_USER_ROLE)

        new_user = user.create_user(admin_form.get('email'), user_role)
        registration_url = url_for('views.register', registration_id=new_user.registration_id)

        return render_template('admin.html', new_user=new_user,
                                             registration_url=registration_url,
                                             users=user.get_users())

    return render_template('admin.html', new_user=None, users=user.get_users())

app/templates/admin.html
{% extends "base.html" %}

{% block title %}Admin{% endblock %}

{% block css %}
<style type="text/css">
  .row {
    padding-bottom: 10px;
  }
</style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-12">
    <h1>Admin <br><small>Remember, with great power comes great responsibility.</small></h1>
  </div>
</div>

<div class="row">
  <form action="" class="form-horizontal" method="post">
    <div class="col-sm-8">
        <div class="input-group">
          <span class="input-group-addon">
            Create User
          </span>
          <input type="email" name="email" class="form-control" placeholder="email" required="" autofocus="">
          <span class="input-group-btn">
            <input class="btn btn-primary" id="add" type="submit" value="Add">
          </span>
        </div>
    </div>



    <label class="control-label col-sm-1" >Role</label>
    <div class="col-sm-3">
      <select name="role" class="form-control">
        <option value="admin">Admin</option>
        <option value="base-user-role" selected>Base User</option>
      </select>
    </div>

  </form>
</div>


{% if new_user %}
  <div class="row">
    <div class="col-sm-12">

      {% if new_user.is_registered %}
        <div class="alert alert-warning">
        {{ new_user.email }} has already been registered.
      {% else %}
        <div class="alert alert-success">
        {{ new_user.email }} was successfully created! You can register this account <a href="{{ registration_url }}">here</a>!
      {% endif %}

      </div>
    </div>
  </div>
{% endif %}

<div class="row">
  <div class="col-sm-12">
    <h1>User Directory</h1>
  </div>
</div>

<div class="row">
  <div class="form-group col-sm-12">
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Email</th>
        <th>Role</th>
        <th>Is Registered</th>
        <th>Registration ID</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{user.email}}</td>
          <td>{{user.role}}</td>
          <td>{{user.is_registered}}</td>
          <td>{{user.registration_id}}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
</div>

{% endblock %}

{% block js %}{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="./favicon.ico">


    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <style type="text/css">
      body {
        padding-top: 50px;
      }
      .navbar-fixed-top, .navbar-fixed-bottom {
        z-index: 99;
      }
      .container {
        width: auto;
        max-width: 767px;
        padding: 0 15px;
      }
    </style>
    {% block css %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="{%if request.path == url_for('views.home')%}active{%endif%}"><a href="{{ url_for('views.home') }}">Home</a></li>

            {% if current_user.is_authenticated() %}

              <li class="{%if request.path == url_for('views.charts')%}active{%endif%}"><a href="{{ url_for('views.charts') }}">Charts</a></li>
              {% if current_user.is_admin() %}
                <li class="{%if request.path == url_for('views.admin')%}active{%endif%}"><a href="{{ url_for('views.admin') }}">Admin</a></li>
              {% endif %}
            {% endif %}
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
              <li class="" ><a class="disable" href="#">{{ current_user.email }}</a></li>
              <li class=""><a href="{{ url_for('views.logout') }}">Logout</a></li>
            {% else %}
              <li class="{%if request.path == url_for('views.login')%}active{%endif%}"><a href="{{ url_for('views.login') }}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function() {
        $('a.disable').click(function(e) {
          e.preventDefault();
        });
      });
    </script>
    {% block js %}{% endblock %}
  </body>
</html>

app/templates/chart.html
{% extends "base.html" %}

{% block title %}Chart JS Demo{% endblock %}

{% block css %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/nprogress/0.1.2/nprogress.css">
<style type="text/css">
  canvas {
    padding-top: 25px;
  }
  #legend > span {
    padding-right: 25px;
  }
</style>
{% endblock %}


{% block content %}


<div class="row">
  <div class="col-sm-12">
    <h1>Chart <br><small>Show data by...</small></h1>
  </div>
</div>


<div class="row">
  <div class="form-group col-sm-4">
    <label for="student_year">Year</label>
    <select name="student_year" class="form-control" id="student_year">
      <option value="all" selected>all recorded years</option>
      <option value="2012">2012</option>
      <option value="2013" >2013</option>
      <option value="2014">2014</option>
    </select>
  </div>

  <div class="form-group col-sm-4">
    <label for="student_type">Student Property</label>
    <select name="student_type" class="form-control" id="student_type">
      <option value="gpa">GPA</option>
      <option value="age">Age</option>
      <option value="gender">Gender</option>
      <option value="oncampus">Living On/Off Campus</option>
      <option value="major">Major Distribution</option>
      <option value="grade">Grade</option>
    </select>
  </div>
</div>

<div class="row">
  <div class="form-group col-sm-4">
    <label for="college">College of</label>
    <select name="college" class="form-control" id="college">
      <option value="">-</option>
      {% for college in colleges %}
      <option value="{{college}}">{{college}}</option>
      {% endfor %}
    </select>
  </div>

  <div class="form-group col-sm-4">
    <label for="major">Department</label>
    <select name="major" class="form-control" id="major" disabled>
      <option value="">-</option>
    </select>
  </div>
  <div class="form-group col-sm-4">
    <label for="course">Course</label>
    <select name="course" class="form-control" id="course" disabled>
      <option value="">-</option>
    </select>
  </div>
</div>


<div class="row">
  <div class="col-sm-12">
    <input class="btn btn-primary btn-lg pull-right" id="submit" type="submit" value="Update">
  </div>
</div>

<div class="row">
  <div id="legend" class="col-sm-12">

  </div>
</div>

<canvas id="myChart" width="700" height="400"></canvas>

{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.1.2/nprogress.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js"></script>
<script>
    $("#college" ).change(function(e) {
      var element = $(this);
      $.ajax({
        type: 'GET',
        url: '/isu/' + element.val(),
        dataType: 'json',
        complete: function(data){
          var majors = data.responseJSON;
          var newOptions = '<option value="">-</option>';
          for (var i=0; i<majors.length; i++) {
            var major = majors[i];
            newOptions += '<option value="' + major + '">' + major + '</option>';
          }
          $('#major').removeAttr('disabled')
                     .html(newOptions);
        }
      });

    });
</script>
<script>
  Array.min = function( array ){
      return Math.min.apply( Math, array );
  };
  Array.max = function( array ){
      return Math.max.apply( Math, array );
  };
  var isInArray = function(array, search) {
      return (array.indexOf(search) >= 0) ? true : false; 
  };

  $(document).ready(function() {
      NProgress.configure({ trickleRate: 0.10, trickleSpeed: 350 });
    $('#submit').click(function(e) {
      NProgress.start();
      var data = {
        course: $('#course').val(),
        major: $('#major').val(),
        college: $('#college').val(),
        student_type: $('#student_type').val(),
        year: $('#student_year').val(),
      };
      $.ajax({
        type: 'POST',
        url: '{{ url_for("views.charts") }}',
        dataType: 'json',
        data: data,
        complete: function(data){
          NProgress.done();
          var distribution = data.responseJSON.distribution;
          var studentType = $('#student_type').val();

          var graph_data = {
            labels : [],
            datasets : [
              {
                fillColor : "rgba(151,187,205,0.2)",
                strokeColor : "rgba(151,187,205,1)",
                data : []
              },
              {
                fillColor : "rgba(220,220,220,0.2)",
                strokeColor : "rgba(220,220,220,1)",
                data : []
              },
              {
                fillColor : "rgba(151,205,187,0.2)",
                strokeColor : "rgba(151,205,187,1)",
                data : []
              }
            ]
          };

          $('#legend').html('');
          var currentColorIndex = 0;
          var grades = ['A','A-','B+','B','B-','C+','C','C-','D+','D','D-','F'];
          for(var year in distribution) {
            if (distribution.hasOwnProperty(year)) {
              if(studentType == "grade"){
                graph_data.labels.push('A');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["A"]);
                graph_data.labels.push('A-');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["A-"]);
                graph_data.labels.push('B+');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["B+"]);
                graph_data.labels.push('B');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["B"]);
                graph_data.labels.push('B-');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["B-"]);
                graph_data.labels.push('C+');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["C+"]);
                graph_data.labels.push('C');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["C"]);
                graph_data.labels.push('C-');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["C-"]);
                graph_data.labels.push('D+');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["D+"]);
                graph_data.labels.push('D');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["D"]);
                graph_data.labels.push('D-');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["D-"]);
                graph_data.labels.push('F');
                graph_data.datasets[currentColorIndex].data.push(distribution[year]["F"]);
              }
              else {
                for(var distribution_group in distribution[year]) {
                  if(distribution[year].hasOwnProperty(distribution_group)){
                    if (! isInArray(graph_data.labels, distribution_group))
                      graph_data.labels.push(distribution_group);
                    graph_data.datasets[currentColorIndex].data.push(distribution[year][distribution_group]);
                  }
                }
              }


              $('#legend').append([
                '<span style="color:',graph_data.datasets[currentColorIndex].strokeColor,';">',
                year,
                '</span>'].join('')
              );
              currentColorIndex = currentColorIndex + 1;
              
            }
          }

          if(currentColorIndex < 2)
              graph_data.datasets.splice(currentColorIndex, 3 - currentColorIndex);

          if(studentType != "grade") {
              graph_data.labels.sort(function(a, b) {
                return a - b; // I'm cheating some data here...
              });
          }

          var ctx = $("#myChart").get(0).getContext("2d");
          var steps = [];

          for (var i = 0; i < currentColorIndex; i++)
          {
            steps = steps.concat(graph_data.datasets[i].data);
          }

          var options = {
            scaleOverride : true,
            scaleSteps : Array.max(steps) - Array.min(steps)+2,
            scaleStepWidth : 1,
            scaleStartValue : Array.min(steps)-2
          };

          if (studentType === 'gender' || studentType === 'oncampus')
            new Chart(ctx).Bar(graph_data,options);
          else
            new Chart(ctx).Line(graph_data,options);
        }
      });
    });


    $("#major" ).change(function(e) {
      var element = $(this);
      $.ajax({
        type: 'GET',
        url: '/isu/' + element.val(),
        dataType: 'json',
        complete: function(data){
          var courses = data.responseJSON;
          var newOptions = '<option value="">-</option><option value="201">201</option><option value="202">202</option><option value="220">220</option><option value="230">230</option><option value="306">306</option><option value="307">307</option><option value="332">332</option><option value="333">333</option><option value="411">411</option><option value="419A">419A</option><option value="424">424</option><option value="434A">434A</option><option value="451A">451A</option><option value="451B">451B</option><option value="451C">451C</option><option value="451D">451D</option><option value="482C">482C</option><option value="490A">490A</option><option value="490B">490B</option><option value="490C">490C</option><option value="490D">490D</option><option value="490H">490H</option><option value="511">511</option><option value="519">519</option><option value="532">532</option><option value="533">533</option><option value="541">541</option><option value="542">542</option><option value="555">555</option><option value="582C">582C</option><option value="590">590</option><option value="699">699</option>';
          $('#course').removeAttr('disabled')
                     .html(newOptions);
        }
      });

    });


  });
</script>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block css %}
<style type="text/css">

  .jumbotron {
    text-align: center;
    margin-top: 30px;
    background-color: rgba(238, 238, 238, 0.90);
  }

  body {
      background: url(http://farm2.staticflickr.com/1378/5118138509_db47a65c54_o.jpg) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
  }

</style>
{% endblock %}
{% block content %}
<div class="jumbotron">
  <h1>Team April Fools</h1>
  <p class="lead">Welcome to our project demo!</p>
</div>
{% endblock %}

{% block js %}{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block css %}
<style>
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}

.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}

.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}

</style>
{% endblock %}

{% block content %}

  {% if failure %}
<form class="form-signin has-error" action="" method="post">
    <div class="alert alert-danger">Incorrect Email/Password!</div>
  {% else %}

<form class="form-signin" action="" method="post">
  {% endif %}

  <h2 class="">Please sign in</h2>
  <input type="email" name="email" class="form-control" placeholder="email" required="" autofocus="" value="{{ email }}">
  <input type="password" name="password" class="form-control" placeholder="password" required="">

  <input class="btn btn-primary btn-lg pull-right" id="submit" type="submit" value="Sign In">
</form>

{% endblock %}

{% block js %}{% endblock %}

app/templates/modeling.html
{% extends "base.html" %}

{% block title %}Modeling{% endblock %}

{% block css %}{% endblock %}

{% block content %}
<div class="row">
  <h1>Add a Student</h1>

  <div class="form-group col-sm-6">
    <label class="input-name">Name</label>
    <div class="">
      <input type="text" class="form-control" id="input-name" placeholder="For example 'Jon Snow'">
    </div>
  </div>
  <div class="form-group col-sm-6">
    <label for="input-age" class="control-label">Age</label>
    <div class="">
      <input type="number" class="form-control" id="input-age">
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
  <button id="add-student" class="btn btn-primary pull-right">Add</button>
  </div>
</div>


<div class="row">
<h1>All Students</h1>
  <div class="form-group col-sm-12">
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr>
          <td>{{student.name}}</td>
          <td>{{student.age}}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block js %}

<script>
  'use strict';
  $(document).ready(function() {
    var name = $('#input-name');
    var age = $('#input-age');
    $('#add-student').click(function() {
      console.log(name.val());
      console.log(age.val());
      var data = JSON.stringify({
        'name': name.val(),
        'age': age.val()
      });

      $.ajax({
        type: 'POST',
        url: '{{ url_for("views.post_student") }}',
        data: data,
        contentType: 'application/json; charset=utf-8',
        dataType: 'json',
        complete: function(data){
          // wait 400 miliseconds until we reload the page with updated results
          window.setTimeout(function() {
            location.reload();
          }, 400);
        }
      });

    });
  });
</script>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block css %}
<style>
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
}

.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}

</style>
{% endblock %}

{% block content %}

<h2 class="">Welcome, {{ user.email }} please create a password for your account.</h2>

  {% if attempt.get('failure', False) %}
<form class="form-signin has-error" action="" method="post">
    <div class="alert alert-danger">Password must be at least 6 characters!</div>
  {% else %}

<form class="form-signin" action="" method="post">
  {% endif %}


  <input type="password" name="password" class="form-control" placeholder="password" required="" autofocus="">

  <input class="btn btn-primary btn-lg pull-right" id="submit" type="submit" value="Register">
</form>

{% endblock %}

{% block js %}{% endblock %}